apiVersion: apps/v1
kind: Deployment
metadata:
  name: proshop-api
  namespace: proshop
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: proshop-api
  template:
    metadata:
      labels:
        app: proshop-api
        version: v1
    spec:
      containers:
        - name: proshop-api
          image: 402008821676.dkr.ecr.us-east-2.amazonaws.com/proshop/api
          imagePullPolicy: Always
          command: ["bash", "-c", "python manage.py runserver 0.0.0.0:8000"]
          envFrom:
            - configMapRef:
                name: proshop-api
          ports:
            - containerPort: 8000
              name: app
      initContainers:
        - name: init-backend
          image: 402008821676.dkr.ecr.us-east-2.amazonaws.com/proshop/api
          imagePullPolicy: Always
          command: ["./entrypoint.sh"]
          envFrom:
            - configMapRef:
                name: proshop-api
      restartPolicy: Always
