apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proshop

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - literals:
      - DB_NAME=proshop
      - DB_HOST=postgres.proshop.svc.cluster.local
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    name: proshop-api
    namespace: proshop
