apiVersion: v1
kind: Service
metadata:
  name: proshop-api
  namespace: proshop
  labels:
    app: proshop-api
spec:
  type: ClusterIP
  selector:
    app: proshop-api
  ports:
    - port: 8000
      targetPort: 8000
      name: app
