apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proshop

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - literals:
      - API_BASE_URL=""
    name: proshop-ui
    namespace: proshop
