apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proshop-frontend
  namespace: argocd
spec:
  project: default
  destination:
    name: https://kubernetes.default.svc
    namespace: proshop
  source:
    repoURL: https://github.com/jellis18/e-commerce-saas.git
    targetRevision: HEAD
    path: kubernetes/frontend/base
