apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proshop
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: proshop
  source:
    repoURL: https://github.com/jellis18/e-commerce-saas.git
    targetRevision: HEAD
    path: kubernetes/postres/base
