apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proshop-postgres
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: proshop
  source:
    repoURL: https://github.com/jellis18/e-commerce-saas.git
    targetRevision: HEAD
    path: kubernetes/postgres/base
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
