apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: proshop

resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - literals:
      - POSTGRES_DB=proshop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    name: postgres-config
    namespace: proshop
